export enum labels {
  DEFINING_ACCESS = "Defina seu acesso:",
  WELCOMING_MESSAGE = "Bem-vindo ao EAD APP",
  TEACHER = "Professor",
  STUDENT = "Aluno",
  SAYING_HI_TO_STUDENT = "Olá Aluno",
  CLASS = "Aula",
  FRIENDS = "Amigos",
  CONFIG = "Configurações",
  EXIT = "Sair",
  BACK = "Voltar",
  CHOOSE_SUBJECT = "Escolha a matéria que deseja estudar:",
  CHOOSE_QUESTION = "Escolha a questão para fazer:",
  CONTINUE = "CONTINUAR",
  EXP_GAINED = "+ 50xp",
  YOU_ARE_INCREDIBLE = "Você é incrível!",
  CONGRATZ = "Parabéns por acertar a questão!",
  YOU_ARE_WRONG = "Infelizmente você errou.",
  TRY_AGAIN = "Tente novamente!",
  NO_CLASSES_YET = "Ainda não foi iniciada nenhuma aula. Espere seu professor.",
  NO_SUBJECTS_YET = "Não foi encontrada nenhuma matéria. Espere seu professor.",
}
